"""
Interactive 3D scatter plot with time slider for
allen_*_multipos_results.npy generated by simulate_allen.py.

- Input: allen_*_multipos_results.npy (dict saved via np.save(..., allow_pickle=True))
- Output: matplotlib interactive window with 3D scatter and time slider
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Optional

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import RadioButtons
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm


def _find_default_input(script_dir: Path) -> Optional[Path]:
    """Pick the most recently modified allen_*_multipos_results.npy in ./output."""
    outdir = script_dir / "output"
    if not outdir.is_dir():
        return None
    candidates = list(outdir.glob("allen_*_multipos_results.npy"))
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0]


def _load_results(path: Path) -> dict:
    data = np.load(str(path), allow_pickle=True)
    if isinstance(data, np.ndarray) and data.ndim == 0:
        data = data.item()
    if not isinstance(data, dict):
        raise TypeError(f"Unexpected root type in npy: {type(data)}")
    required = ["positions_um", "time_ms", "Vm_mV"]
    for k in required:
        if k not in data:
            raise KeyError(f"Key '{k}' not found in npy. Keys: {list(data.keys())}")
    return data


def make_interactive_3d_scatter(
    positions_um: np.ndarray,
    time_ms: np.ndarray,
    Vm_mV: np.ndarray,
    title_prefix: str = "Allen neuron Vm",
    point_size: float = 3.0,
    vm_clip_percentile: float | None = 99.5,
) -> None:
    """
    matplotlib 3D scatter with time selection via dropdown-like widget (RadioButtons).

    - 오른쪽 패널의 시간 리스트(라디오 버튼)를 클릭해서 프레임 전환
    - Python 창에서 직접 실행되며, 창을 닫을 때까지 대화형으로 사용 가능
    """
    positions_um = np.asarray(positions_um)
    time_ms = np.asarray(time_ms)
    Vm_mV = np.asarray(Vm_mV)

    if positions_um.ndim != 2 or positions_um.shape[1] != 3:
        raise ValueError(f"positions_um shape must be (N, 3), got {positions_um.shape}")
    if Vm_mV.shape[0] != positions_um.shape[0]:
        raise ValueError(f"Vm_mV first dim must match positions. Vm_mV: {Vm_mV.shape}, positions: {positions_um.shape}")
    if Vm_mV.shape[1] != time_ms.shape[0]:
        raise ValueError(f"Vm_mV second dim must match time_ms. Vm_mV: {Vm_mV.shape}, time_ms: {time_ms.shape}")

    n_positions, n_times = Vm_mV.shape

    # 전체 시간/공간에서 절댓값 기준 outlier 제거/클리핑 기준 계산
    abs_all = np.abs(Vm_mV)
    if vm_clip_percentile is not None:
        # 예: 99.5 percentile 기준으로 극단값 잘라내기
        vm_abs_max = float(np.percentile(abs_all, vm_clip_percentile))
    else:
        vm_abs_max = float(abs_all.max())

    if vm_abs_max <= 0.0:
        vm_abs_max = 1.0

    # outlier 위치(어느 시점에서든 |Vm|이 기준을 넘는 위치)는 아예 플롯에서 제외
    keep_mask = abs_all.max(axis=1) <= vm_abs_max
    positions_um = positions_um[keep_mask]
    Vm_mV = Vm_mV[keep_mask, :]

    n_positions, n_times = Vm_mV.shape

    x = positions_um[:, 0]
    y = positions_um[:, 1]
    z = positions_um[:, 2]

    # Figure와 Axes 생성
    fig = plt.figure(figsize=(12, 9))
    # 왼쪽: 3D 플롯, 오른쪽: 시간 선택용 RadioButtons 영역
    ax = fig.add_axes([0.05, 0.10, 0.70, 0.85], projection="3d")

    # 초기 시간 인덱스: 0.20 ms에 가장 가까운 인덱스 선택 (없으면 0)
    target_t_ms = 0.20
    init_idx = int(np.argmin(np.abs(time_ms - target_t_ms))) if n_times > 0 else 0
    
    # 색상 정규화 (0을 중심으로 대칭)
    norm = TwoSlopeNorm(vmin=-vm_abs_max, vcenter=0.0, vmax=vm_abs_max)
    cmap = plt.get_cmap("RdBu_r")

    # 초기 색상/알파 계산
    vm0 = Vm_mV[:, init_idx]
    colors0 = cmap(norm(vm0))  # RGBA
    # 0일 때 완전 투명, |Vm|가 클수록 불투명
    alphas0 = np.clip(np.abs(vm0) / vm_abs_max, 0.0, 1.0)
    colors0[:, 3] = alphas0

    # 초기 scatter plot
    sc = ax.scatter(
        x, y, z,
        c=colors0,
        s=point_size,
        edgecolors="none",
    )

    # Colorbar 추가 (한 번만) - alpha는 무시하고 Vm 값 기준으로만 색상 막대 표시
    from matplotlib.cm import ScalarMappable

    sm = ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, shrink=0.6, pad=0.1)
    cbar.set_label("Vm (mV)", rotation=270, labelpad=20)
    
    # 축 레이블 및 제목
    ax.set_xlabel("x (µm)")
    ax.set_ylabel("y (µm)")
    ax.set_zlabel("z (µm)")
    title_text = ax.text2D(
        0.5,
        0.95,
        f"{title_prefix}  t = {float(time_ms[init_idx]):.3f} ms",
        transform=ax.transAxes,
        ha="center",
        va="top",
    )

    # 오른쪽에 시간 선택용 RadioButtons 영역 생성
    # matplotlib에는 진짜 드롭다운이 없어서, 라디오 버튼 리스트로 대체
    t_labels = [f"{t:.3f} ms" for t in time_ms]
    ax_radio = fig.add_axes([0.80, 0.20, 0.18, 0.70])
    radio = RadioButtons(ax_radio, labels=t_labels, active=init_idx)

    # RadioButtons 콜백 함수
    def on_time_selected(label: str) -> None:
        # label은 "0.200 ms" 형태이지만, RadioButtons는 active index를 들고 있으므로
        # 현재 선택된 인덱스를 그대로 사용
        t_idx = t_labels.index(label)
        t = float(time_ms[t_idx])

        # 새 색상/알파 계산
        vm = Vm_mV[:, t_idx]
        colors = cmap(norm(vm))
        alphas = np.clip(np.abs(vm) / vm_abs_max, 0.0, 1.0)
        colors[:, 3] = alphas

        # scatter 색상만 업데이트
        sc.set_facecolors(colors)

        # 제목 업데이트
        title_text.set_text(f"{title_prefix}  t = {t:.3f} ms")

        fig.canvas.draw_idle()

    radio.on_clicked(on_time_selected)

    plt.show()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Allen multipos Vm results를 시간 슬라이더가 있는 3D matplotlib 스캐터로 시각화합니다."
    )
    parser.add_argument(
        "--input",
        type=str,
        default=None,
        help="Path to allen_*_multipos_results.npy (default: ./output에서 가장 최근 파일 선택)",
    )
    parser.add_argument(
        "--point-size",
        type=float,
        default=1.0,
        help="Scatter plot point size (default: 1.0)",
    )
    parser.add_argument(
        "--vm-clip-percentile",
        type=float,
        default=99.5,
        help=(
            "Vm 절댓값 outlier 제거 기준 퍼센타일 (예: 99.5 → 상위 0.5% 제거). "
            "None으로 두면 outlier 제거 없이 전체 범위 사용."
        ),
    )
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent

    input_path = Path(args.input) if args.input else _find_default_input(script_dir)
    if input_path is None:
        raise SystemExit("입력 파일을 찾을 수 없습니다. ./output/allen_*_multipos_results.npy 를 확인하세요.")
    if not input_path.exists():
        raise SystemExit(f"입력 파일이 존재하지 않습니다: {input_path}")

    data = _load_results(input_path)
    positions_um = np.asarray(data["positions_um"])
    time_ms = np.asarray(data["time_ms"])
    Vm_mV = np.asarray(data["Vm_mV"])

    cell_id = str(data.get("cell_id", "allen"))
    title_prefix = f"Allen {cell_id} Vm"

    print(f"데이터 로드 완료:")
    print(f"  - 위치 수 (원본): {positions_um.shape[0]}")
    print(f"  - 시간 포인트: {len(time_ms)}")
    print(f"  - Vm 범위 (원본): {Vm_mV.min():.2f} ~ {Vm_mV.max():.2f} mV")
    print(f"\n인터랙티브 창이 열립니다. 오른쪽의 시간 리스트에서 보고 싶은 시간을 선택하세요.")
    print(f"창을 닫으면 프로그램이 종료됩니다.")

    make_interactive_3d_scatter(
        positions_um=positions_um,
        time_ms=time_ms,
        Vm_mV=Vm_mV,
        title_prefix=title_prefix,
        point_size=args.point_size,
        vm_clip_percentile=args.vm_clip_percentile,
    )


if __name__ == "__main__":
    main()

